# DO NOT REMOVE the following attributes:
# annotations.codefresh.io/workflow-origin (identifies type of Workflow Template as Promotion Workflow)
# annotations.version (identifies version of Promotion Workflow used)
# annotations.description (identifies intended use of the Promotion Workflow)
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: non-prod-post-echo
  annotations:
    version: 0.0.1
    codefresh.io/workflow-origin: promotion
spec:
  serviceAccountName: promotion-template
  arguments:
    parameters:
    - name: APP_NAME
      value: "TEST"
  entrypoint: non-prod-post-echo
  templates:
  - name: non-prod-post-echo
    script:
      image: alpine
      command:
      - sh
      source: |
        echo "non-prod-post-echo, syncing {{ workflow.parameters.APP_NAME }} "
        sleep 4
