gitops-runtime:
  event-reporters:
    workflow:
      serviceAccount:
        name: codefresh-sa
  global:
    codefresh:
      url: https://sandbox-1.codefresh.io
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      ingress:
        className: nginx-internal
        enabled: true
        hosts:
          - denys-sandbox-1.rnd-sandbox.cf-infra.com
        protocol: https
      name: codefresh
      isConfigurationRuntime: true
  installer:
    skipValidation: true
