apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shared
  labels:
    codefresh.io/entity: 'git-source'
    codefresh.io/internal: 'false'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: cf-git-sources
  sources:
    - repoURL: https://github.com/denis-codefresh/shared-git-source.git
      path: .
      targetRevision: sandbox-1
      directory:
        include: '*'
        exclude: 'charts/*'
        recurse: true
  destination:
    namespace: codefresh
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
